server:
  port: 8764
spring:
  application:
    name: service-turbine

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-client, eureka-client-2
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
